In [1]:
import numpy as np

array1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Завдання 1:")
print(array1d)

Завдання 1:
[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
array2d = np.zeros((3, 3))
print("\nЗавдання 2:")
print(array2d)


Завдання 2:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
random_array = np.random.randint(1, 11, size=(5, 5))
print("\nЗавдання 3:")
print(random_array)


Завдання 3:
[[ 7  7  6 10  8]
 [10  6  1  2  8]
 [ 7  5  8  6  4]
 [ 3  2  7  5  9]
 [10  9  3  2  3]]


In [4]:
random_float_array = np.random.rand(4, 4)
print("\nЗавдання 4:")
print(random_float_array)


Завдання 4:
[[0.32907909 0.2800519  0.08359346 0.68536461]
 [0.7837906  0.13608359 0.68876794 0.9496288 ]
 [0.15327792 0.73454521 0.52321301 0.57250516]
 [0.320041   0.34357601 0.1444465  0.33581031]]


In [5]:
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)
add_result = array1 + array2
sub_result = array1 - array2
mul_result = array1 * array2
print("\nЗавдання 5:")
print("Додавання:", add_result)
print("Віднімання:", sub_result)
print("Множення:", mul_result)


Завдання 5:
Додавання: [13  7 17  7 11]
Віднімання: [-1 -1 -1 -3  1]
Множення: [42 12 72 10 30]


In [6]:
vector1 = np.random.random(7)
vector2 = np.random.random(7)
scalar_product = np.dot(vector1, vector2)
print("\nЗавдання 6:")
print("Скалярний добуток:", scalar_product)


Завдання 6:
Скалярний добуток: 2.0677994322916584


In [7]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))
product_matrix = np.dot(matrix1, matrix2)
print("\nЗавдання 7:")
print("Матричний добуток:")
print(product_matrix)


Завдання 7:
Матричний добуток:
[[ 20  38  30]
 [ 94 181 144]]


In [8]:
matrix3x3 = np.random.randint(1, 11, size=(3, 3))
inverse_matrix = np.linalg.inv(matrix3x3)
print("\nЗавдання 8:")
print("Обернена матриця:")
print(inverse_matrix)


Завдання 8:
Обернена матриця:
[[-0.05426357  0.01550388  0.11627907]
 [-0.03410853  0.12403101 -0.06976744]
 [ 0.14418605 -0.06976744 -0.02325581]]


In [9]:
matrix4x4 = np.random.rand(4, 4)
transposed_matrix = np.transpose(matrix4x4)
print("\nЗавдання 9:")
print("Транспонована матриця:")
print(transposed_matrix)


Завдання 9:
Транспонована матриця:
[[0.71660739 0.27418117 0.51694239 0.36947607]
 [0.73669886 0.14854796 0.45102834 0.24948787]
 [0.02984907 0.11902116 0.28837451 0.16010941]
 [0.76951897 0.96572105 0.93234424 0.30649561]]


In [10]:
matrix3x4 = np.random.randint(1, 11, size=(3, 4))
vector4 = np.random.randint(1, 11, size=4)
result_vector = np.dot(matrix3x4, vector4)
print("\nЗавдання 10:")
print("Результат множення матриці на вектор:")
print(result_vector)


Завдання 10:
Результат множення матриці на вектор:
[120 113 257]


In [11]:
matrix2x3 = np.random.random((2, 3))
vector3 = np.random.random(3)
result_vector = np.dot(matrix2x3, vector3)
print("\nЗавдання 11:")
print("Результат множення матриці на вектор:")
print(result_vector)


Завдання 11:
Результат множення матриці на вектор:
[0.13404792 0.27256666]


In [12]:
matrixA = np.random.randint(1, 11, size=(2, 2))
matrixB = np.random.randint(1, 11, size=(2, 2))
elementwise_product = np.multiply(matrixA, matrixB)
print("\nЗавдання 12:")
print("Поелементне множення матриць:")
print(elementwise_product)


Завдання 12:
Поелементне множення матриць:
[[18 30]
 [42 60]]


In [13]:
matrixA = np.random.randint(1, 11, size=(2, 2))
matrixB = np.random.randint(1, 11, size=(2, 2))
matrix_product = np.dot(matrixA, matrixB)
print("\nЗавдання 13:")
print("Матричний добуток матриць:")
print(matrix_product)


Завдання 13:
Матричний добуток матриць:
[[46 52]
 [36 20]]


In [14]:
matrix5x5 = np.random.randint(1, 101, size=(5, 5))
sum_elements = np.sum(matrix5x5)
print("\nЗавдання 14:")
print("Сума елементів матриці:")
print(sum_elements)


Завдання 14:
Сума елементів матриці:
1425


In [15]:
matrixC = np.random.randint(1, 11, size=(4, 4))
matrixD = np.random.randint(1, 11, size=(4, 4))
matrix_difference = matrixC - matrixD
print("\nЗавдання 15:")
print("Різниця між матрицями:")
print(matrix_difference)


Завдання 15:
Різниця між матрицями:
[[-5 -3  2 -2]
 [-3 -8 -3 -2]
 [ 3  4  2  2]
 [-2 -2  3 -7]]


In [16]:
matrix3x3 = np.random.random((3, 3))
row_sums = np.sum(matrix3x3, axis=1)
column_vector = row_sums.reshape(-1, 1)
print("\nЗавдання 16:")
print("Вектор-стовпчик сум рядків матриці:")
print(column_vector)


Завдання 16:
Вектор-стовпчик сум рядків матриці:
[[1.94125128]
 [2.0871867 ]
 [0.85511575]]


In [17]:
matrixE = np.random.randint(-10, 11, size=(3, 4))
squared_matrix = np.square(matrixE)
print("\nЗавдання 17:")
print("Матриця з квадратами чисел:")
print(squared_matrix)


Завдання 17:
Матриця з квадратами чисел:
[[ 36   1   9  49]
 [ 81   9  49 100]
 [ 16   4  16   4]]


In [18]:
vector5 = np.random.randint(1, 51, size=4)
sqrt_vector = np.sqrt(vector5)
print("\nЗавдання 18:")
print("Вектор з квадратними коренями чисел:")
print(sqrt_vector)


Завдання 18:
Вектор з квадратними коренями чисел:
[6.63324958 4.89897949 5.74456265 1.41421356]
